version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update -yqq
            apt-get install -y cmake git python software-properties-common unzip wget
            add-apt-repository -y ppa:ubuntu-toolchain-r/test
            apt-get update -yqq
            apt-get install -y g++-7
            wget https://cmake.org/files/v3.13/cmake-3.13.0-Linux-x86_64.tar.gz
            tar xf cmake-3.13.0-Linux-x86_64.tar.gz
            git clone https://github.com/KhronosGroup/SPIRV-Headers
            wget -q https://github.com/KhronosGroup/SPIRV-Tools/releases/download/master-tot/SPIRV-Tools-master-linux-RelWithDebInfo.zip
            unzip SPIRV-Tools-master-linux-RelWithDebInfo.zip -d SPIRV-Tools

      - restore_cache:
          key: deqp-vk-ff7282e
      - run:
          name: Build Vulkan CTS
          command: |
            if [ -x VK-GL-CTS/deqp-vk ]; then exit 0; fi
            rm -rf VK-GL-CTS
            git clone https://github.com/KhronosGroup/VK-GL-CTS
            mkdir -p VK-GL-CTS/build
            cd VK-GL-CTS/build
            git checkout ff7282e
            python ../external/fetch_sources.py
            cmake ..
            make -j 4
            cp external/vulkancts/modules/vulkan/deqp-vk ..
      - save_cache:
          key: deqp-vk-ff7282e
          paths:
            - VK-GL-CTS/deqp-vk

      - run:
          name: Build Talvos
          command: |
            git clone https://github.com/talvos/talvos talvos-src
            mkdir -p talvos-src/build
            cd talvos-src/build
            ../../cmake-3.13.0-Linux-x86_64/bin/cmake .. \
              -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_INSTALL_PREFIX=$PWD/../../talvos \
              -DCMAKE_C_COMPILER=gcc-7 \
              -DCMAKE_CXX_COMPILER=g++-7 \
              -DSPIRV_INCLUDE_DIR=$PWD/../../SPIRV-Headers/include/ \
              -DSPIRV_TOOLS_INCLUDE_DIR=$PWD/../../SPIRV-Tools/include/ \
              -DSPIRV_TOOLS_LIBRARY_DIR=$PWD/../../SPIRV-Tools/lib/
            make && make test && make install
