executors:
  base-image:
    docker:
      - image: buildpack-deps:bionic

aliases:
  - &install-base-deps
    run:
      name: Install base dependencies
      command: |
        apt-get update -yqq
        apt-get install -y cmake libgl1-mesa-dev mesa-common-dev ninja-build unzip

version: 2.1
jobs:
  build:
    executor: base-image
    steps:
      - checkout
      - *install-base-deps
      - run:
          name: Install SPIR-V dependencies
          command: |
            git clone https://github.com/KhronosGroup/SPIRV-Headers
            wget -q https://github.com/KhronosGroup/SPIRV-Tools/releases/download/master-tot/SPIRV-Tools-master-linux-RelWithDebInfo.zip
            unzip SPIRV-Tools-master-linux-RelWithDebInfo.zip -d SPIRV-Tools

      - restore_cache:
          key: deqp-vk-ff7282e-v3
      - run:
          name: Build Vulkan CTS
          command: |
            if [ -x VK-GL-CTS/deqp-vk ]; then exit 0; fi
            rm -rf VK-GL-CTS
            git clone https://github.com/KhronosGroup/VK-GL-CTS
            mkdir -p VK-GL-CTS/build
            cd VK-GL-CTS/build
            git checkout ff7282e
            python ../external/fetch_sources.py
            sed -i 's/libvulkan.so.1/libtalvos-vulkan.so/' \
              ../framework/platform/lnx/tcuLnxVulkanPlatform.cpp
            cmake ..
            make -j 4
            cp external/vulkancts/modules/vulkan/deqp-vk ..
            mv external/vulkancts/modules/vulkan/vulkan ..
      - save_cache:
          key: deqp-vk-ff7282e-v3
          paths:
            - VK-GL-CTS/deqp-vk
            - VK-GL-CTS/vulkan

      - run:
          name: Build Talvos
          command: |
            git clone https://github.com/talvos/talvos talvos-src
            mkdir -p talvos-src/build
            cd talvos-src/build
            cmake .. \
              -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_INSTALL_PREFIX=$PWD/../../talvos \
              -DCMAKE_C_COMPILER=gcc-7 \
              -DCMAKE_CXX_COMPILER=g++-7 \
              -DSPIRV_INCLUDE_DIR=$PWD/../../SPIRV-Headers/include/ \
              -DSPIRV_TOOLS_INCLUDE_DIR=$PWD/../../SPIRV-Tools/include/ \
              -DSPIRV_TOOLS_LIBRARY_DIR=$PWD/../../SPIRV-Tools/lib/
            make && make test && make install

      - persist_to_workspace:
          root: .
          paths:
            - talvos
            - VK-GL-CTS

  test:
    executor: base-image
    parameters:
      group:
        type: string
    steps:
      - run: echo
      - checkout
      - *install-base-deps
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          no_output_timeout: 2h
          command: |
            export TALVOS_MAX_ERRORS=1
            export LD_LIBRARY_PATH=$PWD/talvos/lib/:$LD_LIBRARY_PATH
            export PATH=$PWD/VK-GL-CTS:$PATH
            mkdir test-dir
            cd test-dir
            ln -s ../VK-GL-CTS/vulkan
            grep "dEQP-VK\.<< parameters.group >>\." ../vk-default.txt | grep -vxFf ../results/SLOW >TESTS
            python ../classify.py TESTS

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - build
      - test:
          group: info
          requires:
            - build
      - test:
          group: api
          requires:
            - build
      - test:
          group: memory
          requires:
            - build
      - test:
          group: pipeline
          requires:
            - build
      - test:
          group: binding_model
          requires:
            - build
      - test:
          group: spirv_assembly
          requires:
            - build
      - test:
          group: glsl
          requires:
            - build
      - test:
          group: renderpass
          requires:
            - build
      - test:
          group: renderpass2
          requires:
            - build
      - test:
          group: ubo
          requires:
            - build
      - test:
          group: dynamic_state
          requires:
            - build
      - test:
          group: ssbo
          requires:
            - build
      - test:
          group: query_pool
          requires:
            - build
      - test:
          group: draw
          requires:
            - build
      - test:
          group: compute
          requires:
            - build
      - test:
          group: image
          requires:
            - build
      - test:
          group: wsi
          requires:
            - build
      - test:
          group: synchronization
          requires:
            - build
      - test:
          group: sparse_resources
          requires:
            - build
      - test:
          group: tessellation
          requires:
            - build
      - test:
          group: rasterization
          requires:
            - build
      - test:
          group: clipping
          requires:
            - build
      - test:
          group: fragment_operations
          requires:
            - build
      - test:
          group: texture
          requires:
            - build
      - test:
          group: geometry
          requires:
            - build
      - test:
          group: robustness
          requires:
            - build
      - test:
          group: multiview
          requires:
            - build
      - test:
          group: subgroups
          requires:
            - build
      - test:
          group: ycbcr
          requires:
            - build
      - test:
          group: protected_memory
          requires:
            - build
      - test:
          group: device_group
          requires:
            - build
